### ISSUE TITLE
Add support for disabling health checks

### ISSUE THREAD

**Issue by thomasdarimont** [thomasdarimont/keycloak-health-checks#1]
In some environments like stateless containers some checks might not be needed.
There should be a way to disable a given health.
Perhaps in the provider config or via System Property or ENV-Variable.

**Comment by micahben** [comment]
This is built into the provider config. For example, if you run
```
/subsystem=keycloak-server/spi=health/:add
/subsystem=keycloak-server/spi=health/provider=filesystem-health/:add(enabled=false)
```
through the `jboss-cli`, then `GET /auth/realms/master/health/check` will not run the filesystem health check.

**Comment by thomasdarimont** [comment]
Thanks @micahben I all add this to the docs!
