### ISSUE TITLE
Update for use in Keycloak 13.0.0

### ISSUE THREAD

**Issue by micahben** [thomasdarimont/keycloak-health-checks#14]
Currently this extension uses Keycloak dependencies at version 4.8.3.Final. At the time of this writing, the latest version of Keycloak is 14.0.0, however version 13.0.0 was released about a month and a half ago, so it would be useful to have a version that is compatible with 13.0.0 as well.

**Comment by micahben** [comment]
@thomasdarimont I'm not sure if you monitor this repository anymore, but in case you do, I've opened a PR for this issue.

**Comment by thomasdarimont** [comment]
Fixed via e2674c4
