### ISSUE TITLE
Update for use in Keycloak 14.0.0

### ISSUE THREAD

**Issue by micahben** [thomasdarimont/keycloak-health-checks#15]
Currently this extension uses Keycloak dependencies at version 4.8.3.Final. An [issue exists to update dependencies to Keycloak 13.0.0](https://github.com/thomasdarimont/keycloak-health-checks/issues/14). At the time of this writing, the latest version of Keycloak is 14.0.0.

**Comment by thomasdarimont** [comment]
Superseded by 34c5d4e
