### ISSUE TITLE
Configuration examples given in README.md not compatible with later versions of KeyCloak

### ISSUE THREAD

**Issue by SamTheisens** [thomasdarimont/keycloak-health-checks#8]
Because KeyCloak has gone through several upgrades of WildFly and the `module.xml` example in the README is no longer compatible with later versions of KeyCloak
For example, I had to change the `module.xml` to this: 
```
<?xml version='1.0' encoding='UTF-8'?>
<module xmlns="urn:jboss:module:1.1" name="com.github.thomasdarimont.keycloak.extensions.keycloak-health-checks">

    <resources>
        <resource-root path="keycloak-health-checks-4.8.3.0-SNAPSHOT.jar"/>
    </resources>

    <dependencies>
        <module name="org.keycloak.keycloak-core"/>
        <module name="org.keycloak.keycloak-services"/>
        <module name="org.keycloak.keycloak-server-spi"/>
        <module name="org.keycloak.keycloak-server-spi-private"/>
        <module name="javax.api"/>
        <module name="javax.ws.rs.api"/>
        <module name="com.fasterxml.jackson.core.jackson-core"/>
        <module name="com.fasterxml.jackson.core.jackson-databind"/>
        <module name="com.fasterxml.jackson.core.jackson-annotations"/>
        <module name="org.jboss.logging"/>
        <module name="org.infinispan"/>
        <module name="org.infinispan.commons"/>
    </dependencies>
</module>
```
to get the extension to load.

The way I acquired this configuration was by first configuring via the jboss cli and then capturing the xml from the filesystem.
I realise that you don't claim the extension to work with any other version than KeyCloak 4.8.3.Final (although I can tell it works on 6.0.1 as well 👍), but maybe it would be an idea to either remove the example .xml from the README.md or add a warning that it's best to use the jbos cli.

**Comment by thomasdarimont** [comment]
The example has been updated for the lastest Keycloak version 15.0.2
